version: "3.9"
    
services:
  db:
    image: mysql:8.0.25
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    ports:
     - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mudar@123
      MYSQL_DATABASE: db_controle_financeiro 

volumes:
  db_data: {}